SRC_PATH=/root/src/cpp/wzq_project/src
include  $(SRC_PATH)/MakeCommon

INC_DIR=$(INC_PATH)

USR_FLAGS=-D_DEBUG_
USR_INCLUDE= -I.
APP_LIB=-L$(LIB_PATH)

SRCS=shm.o readIni.o

#target
STATIC_LIBRARY = 

SHARE_LIBRARY = libComponent.so

OUTPUT = 



include  $(SRC_PATH)/MakeCmd
