SRC_PATH=/home/wzq/src
include  $(SRC_PATH)/MakeCommon

INC_DIR=$(INC_PATH)

USR_FLAGS=-D_DEBUG_
USR_INCLUDE= -I.
APP_LIB=-L$(LIB_PATH)/ -lComponent -pthread

SRCS=app_shm.o 

#target
STATIC_LIBRARY = 

SHARE_LIBRARY = 

OUTPUT = app_shm



include  $(SRC_PATH)/MakeCmd